# -*- mode: ruby -*-
# vi: set ft=ruby :

load "provisioner/master.rb"
load "provisioner/node.rb"

VAGRANTFILE_API_VERSION = "2"

DC_NUM = 2
SERVER_NUM = 3
CLIENT_NUM = 3
IP_BASE = "192.168.33"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/coreos-beta"

  (1..DC_NUM).each do |i|
    master = i == 1 ? true : false
    hostname = "dc#{i}"
    ip = "#{IP_BASE}.#{i+10}"

    config.vm.define vm_name = hostname do |dc|
      dc.vm.hostname = hostname
      dc.vm.network :private_network, ip: ip

      # coreos cloudinit
      if master
        dc.vm.provision :file, preserve_order: true, source: "cloud_config/master.yml", destination: "./cloud_config.yml"
      else
        dc.vm.provision :file, preserve_order: true, source: "cloud_config/node.yml", destination: "./cloud_config.yml"
      end
      dc.vm.provision :shell, preserve_order: true do |sh|
        sh.inline = <<-EOT
          sed -e \'s/%master-ip%/#{IP_BASE}.11/g\' -i ./cloud_config.yml
          sed -e \'s/%ip%/#{ip}/g\' -i ./cloud_config.yml
          coreos-cloudinit -from-file=./cloud_config.yml
        EOT
      end

      # provision datacenters
      if master
        provision_master(dc, hostname, ip, SERVER_NUM, CLIENT_NUM)
      else
        master_ip = "#{IP_BASE}.11"
        provision_node(dc, hostname, ip, master_ip, SERVER_NUM, CLIENT_NUM)
      end
    end
  end
end
